---
kind: pipeline
name: go-1-11

steps:
  - name: test-lint-build
    image: golang:1.11
    volumes:
      - name: deps
        path: /go
    commands:
      - make test COVERAGE_FILE=coverage.txt
      - make lint
      - make build

  - name: coverage
    image: plugins/codecov
    settings:
      required: true
      token:
        from_secret: codecov_token
    files:
     - coverage.txt

volumes:
  - name: deps
    temp: {}

---
kind: pipeline
name: release

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: release
    image: golang:1.12
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - make release

trigger:
  event:
  - tag

depends_on:
  - go-1-11
---
kind: signature
hmac: 45d7c2ddfde4c90438e05bdeda5933783f125fcf2098ef2eeaaf4714fe74a95b

...
