project_name: gphotos-uploader-cli
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w {{ .Env.RELEASE_VERSION_TAG }}
checksum:
  name_template: 'checksums.txt'
brews:
  - tap:
      owner: gphotosuploader
      name: homebrew-tap
    folder: Formula
    commit_author:
      name: pacoorozco
      email: paco@pacoorozco.info
    homepage: https://github.com/gphotosuploader/gphotos-uploader-cli
    description: "Mass upload media folders to your Google Photos account(s)"
    test: system "#{bin}/gphotos-uploader-cli --help"
    install: bin.install "gphotos-uploader-cli"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - 'CHANGELOG'
      - 'Merge pull request'
      - 'Merge branch'
