project_name: gphotos-uploader-cli
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w {{ .Env.RELEASE_VERSION_TAG }}
checksum:
  name_template: 'checksums.txt'
