project_name: gphotos-uploader-cli
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w {{ .Env.RELEASE_VERSION_TAG }}
checksum:
  name_template: 'checksums.txt'
brews:
  - github:
      owner: gphotosuploader
      name: homebrew-tap
    folder: Formula
    commit_author:
      name: pacoorozco
      email: paco@pacoorozco.info
    homepage: https://github.com/gphotosuploader/gphotos-uploader-cli
    description: "Mass upload media folders to your Google Photos account(s)"
    test: system "#{bin}/gphotos-uploader-cli --help"
    install: bin.install "gphotos-uploader-cli"
snapcrafts:
  -
    name: gphotos-uploader
    publish: true
    summary: "Mass upload media folders to your Google Photos account(s)"
    description: "This is a CLI to mass upload folders of media to Google Photos. Install it and run it!"

    # A guardrail to prevent you from releasing a snap to all your users before
    # it is ready.
    # `devel` will let you release only to the `edge` and `beta` channels in the
    # store. `stable` will let you release also to the `candidate` and `stable`
    # channels. More info about channels here:
    # https://snapcraft.io/docs/reference/channels
    grade: devel

    # Snaps can be setup to follow three different confinement policies:
    # `strict`, `devmode` and `classic`. A strict confinement where the snap
    # can only read and write in its own namespace is recommended. Extra
    # permissions for strict snaps can be declared as `plugs` for the app, which
    # are explained later. More info about confinement here:
    # https://snapcraft.io/docs/reference/confinement
    confinement: devmode

    license: MIT

    # A snap of type base to be used as the execution environment for this snap.
    # Valid values are:
    # * bare - Empty base snap;
    # * core - Ubuntu Core 16;
    # * core18 - Ubuntu Core 18.
    # Default is empty.
    base: core18
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - 'CHANGELOG'
      - 'Merge pull request'
      - 'Merge branch'