language: go

addons:
  apt:
    packages:
      # needed for the snap pipe:
      - snapd

env:
- GO111MODULE=on
# needed for the snap pipe:
- PATH=/snap/bin:$PATH

go:
- "1.11.x"

script:
- make lint
- make test
- make release

install:
# needed for the snap pipe:
- sudo snap install snapcraft --classic

after_success:
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
