language: go
env:
  global:
  - GO111MODULE=on
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: 1.11.x
before_install:
- go get github.com/mitchellh/gox
install:
- 
script:
- diff -u <(echo -n) <(gofmt -d .)
- go vet $(go list ./... | grep -v /vendor/) || true
- go test -v -race ./...
- if [ "${LATEST}" = "true" ]; then gox -os="linux darwin" -arch="amd64" -output="gphotos-uploader-cli.{{.OS}}.{{.Arch}}"
  -ldflags "-X main.BuildRev=`git rev-parse --short HEAD`" -verbose ./...; fi

deploy:
  provider: releases
  api_key:
    secure: T/IJF5igOS/Fm6gi+V0VZcUjXxy3h2TxtEDg0a19DjnDRxXmZxDn+yEm8c9/3K3oorwMqEA766GHxyPcmVEpDPg5KgSJHNFXJCSF48fLoyaNpz3J4vti3LuUJdixgyhRnuZzgUovmEW0/O52tvaRNj5pkaYD74KFdZ+seGGoFlTPsrQpHzukmGu/tkpSkZnRuF+XxpjBLN7wHMGZyAKGh/e6vsL30N0rr+pvhgDrsnSNHg/qYG5rIVs5cwwWLoK9M4d5iHIEx4rwvbaxaKhveKUmJsN1+ueyr5TZfbVHD0ePHbO9DWcfCuRK65dnH0xue7j/FH029A8i/u4+/iAstaLzMGLUfZWTL1exVlQJFPARYSglReK1XoCBj++CnyX4zLOPq3oz4950VA3RPFWe7nAZpbtO5a5tEobLA9Kyc6o4XwzA0MFgFwYY7Sp2aoRmzfdy6k62aRxV3m6Vr8skMnsEa7j+0jB8MCYpwqsMsBFmH7ZYJVa4JX/ATFwoASBftlLIm2i4+eoyTV3y4Z8AEwA4xfuVM81rVj2F0WTHEbx03acw5SQFNhbJAjopAJjPNkRlXdjJclBpZW2gjKOwI0BgUdtSgfbSt+V7KCSF0hjUFLK5W0pODVetdN+FqsWGy5Nu5P0RCkR4mQ703j22SWmirVOYVeDNKKgfeueEyeg=
  file:
    - gphotos-uploader-cli.darwin.amd64
    - gphotos-uploader-cli.linux.amd64
